/*  			DirectSound
 *
 * Copyright 2010 Chris Robinson
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#ifndef EAX_H
#define EAX_H

#include "eax4.h"

#ifndef EAXVECTOR_DEFINED
#define EAXVECTOR_DEFINED
typedef struct _EAXVECTOR {
    float x, y, z;
} EAXVECTOR;
#endif

/* EAX 3.0 stuff. */
DEFINE_GUID(DSPROPSETID_EAX30_ListenerProperties, 0xa8fa6882, 0xb476, 0x11d3, 0xbd, 0xb9, 0x00, 0xc0, 0xf0, 0x2d, 0xdf, 0x87);
typedef enum {
    DSPROPERTY_EAX30LISTENER_NONE,
    DSPROPERTY_EAX30LISTENER_ALLPARAMETERS,
    DSPROPERTY_EAX30LISTENER_ENVIRONMENT,
    DSPROPERTY_EAX30LISTENER_ENVIRONMENTSIZE,
    DSPROPERTY_EAX30LISTENER_ENVIRONMENTDIFFUSION,
    DSPROPERTY_EAX30LISTENER_ROOM,
    DSPROPERTY_EAX30LISTENER_ROOMHF,
    DSPROPERTY_EAX30LISTENER_ROOMLF,
    DSPROPERTY_EAX30LISTENER_DECAYTIME,
    DSPROPERTY_EAX30LISTENER_DECAYHFRATIO,
    DSPROPERTY_EAX30LISTENER_DECAYLFRATIO,
    DSPROPERTY_EAX30LISTENER_REFLECTIONS,
    DSPROPERTY_EAX30LISTENER_REFLECTIONSDELAY,
    DSPROPERTY_EAX30LISTENER_REFLECTIONSPAN,
    DSPROPERTY_EAX30LISTENER_REVERB,
    DSPROPERTY_EAX30LISTENER_REVERBDELAY,
    DSPROPERTY_EAX30LISTENER_REVERBPAN,
    DSPROPERTY_EAX30LISTENER_ECHOTIME,
    DSPROPERTY_EAX30LISTENER_ECHODEPTH,
    DSPROPERTY_EAX30LISTENER_MODULATIONTIME,
    DSPROPERTY_EAX30LISTENER_MODULATIONDEPTH,
    DSPROPERTY_EAX30LISTENER_AIRABSORPTIONHF,
    DSPROPERTY_EAX30LISTENER_HFREFERENCE,
    DSPROPERTY_EAX30LISTENER_LFREFERENCE,
    DSPROPERTY_EAX30LISTENER_ROOMROLLOFFFACTOR,
    DSPROPERTY_EAX30LISTENER_FLAGS
} DSPROPERTY_EAX30_LISTENERPROPERTY;

/* Stores the value being set, but does not apply it */
#define DSPROPERTY_EAX30LISTENER_DEFERRED               0x80000000
/* The lack of the deferred flag forces a call to CommitDeferredSettings(),
 * applying *all* deferred settings, including the EAX property being set */
#define DSPROPERTY_EAX30LISTENER_IMMEDIATE              0x00000000
/* Same as IMMEDIATE; causes a commit of deferred properties but implies no
 * extra property being set */
#define DSPROPERTY_EAX30LISTENER_COMMITDEFERREDSETTINGS 0x00000000

typedef struct _EAX30LISTENERPROPERTIES {
    DWORD dwEnvironment;
    float flEnvironmentSize;
    float flEnvironmentDiffusion;
    long lRoom;
    long lRoomHF;
    long lRoomLF;
    float flDecayTime;
    float flDecayHFRatio;
    float flDecayLFRatio;
    long lReflections;
    float flReflectionsDelay;
    EAXVECTOR vReflectionsPan;
    long lReverb;
    float flReverbDelay;
    EAXVECTOR vReverbPan;
    float flEchoTime;
    float flEchoDepth;
    float flModulationTime;
    float flModulationDepth;
    float flAirAbsorptionHF;
    float flHFReference;
    float flLFReference;
    float flRoomRolloffFactor;
    DWORD dwFlags;
} EAX30LISTENERPROPERTIES, *LPEAX30LISTENERPROPERTIES;

/* DSPROPERTY_EAX30LISTENER_ENVIRONMENT */
#ifndef EAX_ENVIRONMENTS_DEFINED
#define EAX_ENVIRONMENTS_DEFINED
enum {
    EAX_ENVIRONMENT_GENERIC,
    EAX_ENVIRONMENT_PADDEDCELL,
    EAX_ENVIRONMENT_ROOM,
    EAX_ENVIRONMENT_BATHROOM,
    EAX_ENVIRONMENT_LIVINGROOM,
    EAX_ENVIRONMENT_STONEROOM,
    EAX_ENVIRONMENT_AUDITORIUM,
    EAX_ENVIRONMENT_CONCERTHALL,
    EAX_ENVIRONMENT_CAVE,
    EAX_ENVIRONMENT_ARENA,
    EAX_ENVIRONMENT_HANGAR,
    EAX_ENVIRONMENT_CARPETEDHALLWAY,
    EAX_ENVIRONMENT_HALLWAY,
    EAX_ENVIRONMENT_STONECORRIDOR,
    EAX_ENVIRONMENT_ALLEY,
    EAX_ENVIRONMENT_FOREST,
    EAX_ENVIRONMENT_CITY,
    EAX_ENVIRONMENT_MOUNTAINS,
    EAX_ENVIRONMENT_QUARRY,
    EAX_ENVIRONMENT_PLAIN,
    EAX_ENVIRONMENT_PARKINGLOT,
    EAX_ENVIRONMENT_SEWERPIPE,
    EAX_ENVIRONMENT_UNDERWATER,
    EAX_ENVIRONMENT_DRUGGED,
    EAX_ENVIRONMENT_DIZZY,
    EAX_ENVIRONMENT_PSYCHOTIC,

    EAX_ENVIRONMENT_UNDEFINED,

    EAX_ENVIRONMENT_COUNT
};
#endif

/* DSPROPERTY_EAX30LISTENER_FLAGS */
/* These flags determine what properties are modified when the environment size
 * is changed.
 */
#define EAX30LISTENERFLAGS_DECAYTIMESCALE        0x00000001
#define EAX30LISTENERFLAGS_REFLECTIONSSCALE      0x00000002
#define EAX30LISTENERFLAGS_REFLECTIONSDELAYSCALE 0x00000004
#define EAX30LISTENERFLAGS_REVERBSCALE           0x00000008
#define EAX30LISTENERFLAGS_REVERBDELAYSCALE      0x00000010
/* This flag limits the high frequency decay according to air absorption */
#define EAX30LISTENERFLAGS_DECAYHFLIMIT          0x00000020
#define EAX30LISTENERFLAGS_ECHOTIMESCALE         0x00000040
#define EAX30LISTENERFLAGS_MODTIMESCALE          0x00000080


DEFINE_GUID(DSPROPSETID_EAX30_BufferProperties, 0xa8fa6881, 0xb476, 0x11d3, 0xbd, 0xb9, 0x00, 0xc0, 0xf0, 0x2d, 0xdf, 0x87);
typedef enum {
    DSPROPERTY_EAX30BUFFER_NONE,
    DSPROPERTY_EAX30BUFFER_ALLPARAMETERS,
    DSPROPERTY_EAX30BUFFER_OBSTRUCTIONPARAMETERS,
    DSPROPERTY_EAX30BUFFER_OCCLUSIONPARAMETERS,
    DSPROPERTY_EAX30BUFFER_EXCLUSIONPARAMETERS,
    DSPROPERTY_EAX30BUFFER_DIRECT,
    DSPROPERTY_EAX30BUFFER_DIRECTHF,
    DSPROPERTY_EAX30BUFFER_ROOM,
    DSPROPERTY_EAX30BUFFER_ROOMHF,
    DSPROPERTY_EAX30BUFFER_OBSTRUCTION,
    DSPROPERTY_EAX30BUFFER_OBSTRUCTIONLFRATIO,
    DSPROPERTY_EAX30BUFFER_OCCLUSION,
    DSPROPERTY_EAX30BUFFER_OCCLUSIONLFRATIO,
    DSPROPERTY_EAX30BUFFER_OCCLUSIONROOMRATIO,
    DSPROPERTY_EAX30BUFFER_OCCLUSIONDIRECTRATIO,
    DSPROPERTY_EAX30BUFFER_EXCLUSION,
    DSPROPERTY_EAX30BUFFER_EXCLUSIONLFRATIO,
    DSPROPERTY_EAX30BUFFER_OUTSIDEVOLUMEHF,
    DSPROPERTY_EAX30BUFFER_DOPPLERFACTOR,
    DSPROPERTY_EAX30BUFFER_ROLLOFFFACTOR,
    DSPROPERTY_EAX30BUFFER_ROOMROLLOFFFACTOR,
    DSPROPERTY_EAX30BUFFER_AIRABSORPTIONFACTOR,
    DSPROPERTY_EAX30BUFFER_FLAGS
} DSPROPERTY_EAX30_BUFFERPROPERTY;

#define DSPROPERTY_EAX30BUFFER_DEFERRED               0x80000000
/* NOTE: This applies all deferred changes, not just the buffer's. */
#define DSPROPERTY_EAX30BUFFER_IMMEDIATE              0x00000000
#define DSPROPERTY_EAX30BUFFER_COMMITDEFERREDSETTINGS 0x00000000

/* DSPROPERTY_EAX30BUFFER_ALLPARAMETERS */
typedef struct _EAX30BUFFERPROPERTIES {
    long  lDirect;
    long  lDirectHF;
    long  lRoom;
    long  lRoomHF;
    long  lObstruction;
    float flObstructionLFRatio;
    long  lOcclusion;
    float flOcclusionLFRatio;
    float flOcclusionRoomRatio;
    float flOcclusionDirectRatio;
    long  lExclusion;
    float flExclusionLFRatio;
    long  lOutsideVolumeHF;
    float flDopplerFactor;
    float flRolloffFactor; /* NOTE: Added to listener value, not multiplied. */
    float flRoomRolloffFactor;
    float flAirAbsorptionFactor;
    DWORD dwFlags;
} EAX30BUFFERPROPERTIES, *LPEAX30BUFFERPROPERTIES;

/* DSPROPERTY_EAX30BUFFER_OBSTRUCTION */
#ifndef EAX_OBSTRUCTIONPROPERTIES_DEFINED
#define EAX_OBSTRUCTIONPROPERTIES_DEFINED
typedef struct _EAXOBSTRUCTIONPROPERTIES {
    long  lObstruction;
    float flObstructionLFRatio;
} EAXOBSTRUCTIONPROPERTIES, *LPEAXOBSTRUCTIONPROPERTIES;
#endif

/* DSPROPERTY_EAX30BUFFER_OCCLUSION */
#ifndef EAX_OCCLUSIONPROPERTIES_DEFINED
#define EAX_OCCLUSIONPROPERTIES_DEFINED
typedef struct _EAXOCCLUSIONPROPERTIES {
    long  lOcclusion;
    float flOcclusionLFRatio;
    float flOcclusionRoomRatio;
    float flOcclusionDirectRatio;
} EAXOCCLUSIONPROPERTIES, *LPEAXOCCLUSIONPROPERTIES;
#endif

/* DSPROPERTY_EAX30BUFFER_EXCLUSION */
#ifndef EAX_EXCLUSIONPROPERTIES_DEFINED
#define EAX_EXCLUSIONPROPERTIES_DEFINED
typedef struct _EAXEXCLUSIONPROPERTIES {
    long  lExclusion;
    float flExclusionLFRatio;
} EAXEXCLUSIONPROPERTIES, *LPEAXEXCLUSIONPROPERTIES;
#endif

/* DSPROPERTY_EAX30BUFFER_FLAGS */
#define EAX30BUFFERFLAGS_DIRECTHFAUTO 0x00000001
#define EAX30BUFFERFLAGS_ROOMAUTO     0x00000002
#define EAX30BUFFERFLAGS_ROOMHFAUTO   0x00000004


/* EAX 2.0 stuff. */
DEFINE_GUID(DSPROPSETID_EAX20_ListenerProperties, 0x0306a6a8, 0xb224, 0x11d2, 0x99, 0xe5, 0x00, 0x00, 0xe8, 0xd8, 0xc7, 0x22);
typedef enum {
    DSPROPERTY_EAX20LISTENER_NONE,
    DSPROPERTY_EAX20LISTENER_ALLPARAMETERS,
    DSPROPERTY_EAX20LISTENER_ROOM,
    DSPROPERTY_EAX20LISTENER_ROOMHF,
    DSPROPERTY_EAX20LISTENER_ROOMROLLOFFFACTOR,
    DSPROPERTY_EAX20LISTENER_DECAYTIME,
    DSPROPERTY_EAX20LISTENER_DECAYHFRATIO,
    DSPROPERTY_EAX20LISTENER_REFLECTIONS,
    DSPROPERTY_EAX20LISTENER_REFLECTIONSDELAY,
    DSPROPERTY_EAX20LISTENER_REVERB,
    DSPROPERTY_EAX20LISTENER_REVERBDELAY,
    DSPROPERTY_EAX20LISTENER_ENVIRONMENT,
    DSPROPERTY_EAX20LISTENER_ENVIRONMENTSIZE,
    DSPROPERTY_EAX20LISTENER_ENVIRONMENTDIFFUSION,
    DSPROPERTY_EAX20LISTENER_AIRABSORPTIONHF,
    DSPROPERTY_EAX20LISTENER_FLAGS
} DSPROPERTY_EAX20_LISTENERPROPERTY;

#define DSPROPERTY_EAX20LISTENER_DEFERRED               0x80000000
#define DSPROPERTY_EAX20LISTENER_IMMEDIATE              0x00000000
#define DSPROPERTY_EAX20LISTENER_COMMITDEFERREDSETTINGS 0x00000000

typedef struct _EAX20LISTENERPROPERTIES {
    long lRoom;
    long lRoomHF;
    float flRoomRolloffFactor;
    float flDecayTime;
    float flDecayHFRatio;
    long lReflections;
    float flReflectionsDelay;
    long lReverb;
    float flReverbDelay;
    DWORD dwEnvironment;
    float flEnvironmentSize;
    float flEnvironmentDiffusion;
    float flAirAbsorptionHF;
    DWORD dwFlags;
} EAX20LISTENERPROPERTIES, *LPEAX20LISTENERPROPERTIES;

#define EAX20LISTENERFLAGS_DECAYTIMESCALE        0x00000001
#define EAX20LISTENERFLAGS_REFLECTIONSSCALE      0x00000002
#define EAX20LISTENERFLAGS_REFLECTIONSDELAYSCALE 0x00000004
#define EAX20LISTENERFLAGS_REVERBSCALE           0x00000008
#define EAX20LISTENERFLAGS_REVERBDELAYSCALE      0x00000010
#define EAX20LISTENERFLAGS_DECAYHFLIMIT          0x00000020


DEFINE_GUID(DSPROPSETID_EAX20_BufferProperties, 0x0306a6a7, 0xb224, 0x11d2, 0x99, 0xe5, 0x00, 0x00, 0xe8, 0xd8, 0xc7, 0x22);
typedef enum {
    DSPROPERTY_EAX20BUFFER_NONE,
    DSPROPERTY_EAX20BUFFER_ALLPARAMETERS,
    DSPROPERTY_EAX20BUFFER_DIRECT,
    DSPROPERTY_EAX20BUFFER_DIRECTHF,
    DSPROPERTY_EAX20BUFFER_ROOM,
    DSPROPERTY_EAX20BUFFER_ROOMHF,
    DSPROPERTY_EAX20BUFFER_ROOMROLLOFFFACTOR,
    DSPROPERTY_EAX20BUFFER_OBSTRUCTION,
    DSPROPERTY_EAX20BUFFER_OBSTRUCTIONLFRATIO,
    DSPROPERTY_EAX20BUFFER_OCCLUSION,
    DSPROPERTY_EAX20BUFFER_OCCLUSIONLFRATIO,
    DSPROPERTY_EAX20BUFFER_OCCLUSIONROOMRATIO,
    DSPROPERTY_EAX20BUFFER_OUTSIDEVOLUMEHF,
    DSPROPERTY_EAX20BUFFER_AIRABSORPTIONFACTOR,
    DSPROPERTY_EAX20BUFFER_FLAGS
} DSPROPERTY_EAX20_BUFFERPROPERTY;

#define DSPROPERTY_EAX20BUFFER_DEFERRED               0x80000000
#define DSPROPERTY_EAX20BUFFER_IMMEDIATE              0x00000000
#define DSPROPERTY_EAX20BUFFER_COMMITDEFERREDSETTINGS 0x00000000

typedef struct _EAX20BUFFERPROPERTIES {
    long lDirect;
    long lDirectHF;
    long lRoom;
    long lRoomHF;
    float flRoomRolloffFactor;
    long lObstruction;
    float flObstructionLFRatio;
    long lOcclusion;
    float flOcclusionLFRatio;
    float flOcclusionRoomRatio;
    long lOutsideVolumeHF;
    float flAirAbsorptionFactor;
    DWORD dwFlags;
} EAX20BUFFERPROPERTIES, *LPEAX20BUFFERPROPERTIES;

#define EAX20BUFFERFLAGS_DIRECTHFAUTO 0x00000001
#define EAX20BUFFERFLAGS_ROOMAUTO     0x00000002
#define EAX20BUFFERFLAGS_ROOMHFAUTO   0x00000004


/* EAX 1.0 stuff. */
DEFINE_GUID(DSPROPSETID_EAX10_ListenerProperties, 0x4a4e6fc1, 0xc341, 0x11d1, 0xb7, 0x3a, 0x44, 0x45, 0x53, 0x54, 0x00, 0x00);
typedef enum {
    DSPROPERTY_EAX10LISTENER_ALL,
    DSPROPERTY_EAX10LISTENER_ENVIRONMENT,
    DSPROPERTY_EAX10LISTENER_VOLUME,
    DSPROPERTY_EAX10LISTENER_DECAYTIME,
    DSPROPERTY_EAX10LISTENER_DAMPING
} DSPROPERTY_EAX10_REVERBPROPERTY;

typedef struct {
    DWORD dwEnvironment;
    float fVolume;
    float fDecayTime;
    float fDamping;
} EAX10LISTENERPROPERTIES;


DEFINE_GUID(DSPROPSETID_EAX10_BufferProperties, 0x4a4e6fc0, 0xc341, 0x11d1, 0xb7, 0x3a, 0x44, 0x45, 0x53, 0x54, 0x00, 0x00);
typedef enum {
    DSPROPERTY_EAX10BUFFER_ALL,
    DSPROPERTY_EAX10BUFFER_REVERBMIX
} DSPROPERTY_EAX10_BUFFERPROPERTY;

typedef struct {
    float fMix;
} EAX10BUFFERPROPERTIES;

#endif /* EAX_H */
